### ISSUE TITLE
error while signing in to google

### ISSUE THREAD

**Issue by johnpatrick9** [ParveenBhadooOfficial/Bhadoo-Cloud-Drive#2]
Hello,I have recently depolyed the herokuapp but I keep getting an error when I try to sign into google,could you please help me out? @ParveenBhadooOfficial  and this is the error
 
400. That’s an error.

Error: redirect_uri_mismatch

The redirect URI in the request, https://kamena9978.herokuapp.com/api/oauth/google/callback, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/167354703985-vvq2m7brksm8aal41ie8bfnnk4mbm91s.apps.googleusercontent.com?project=167354703985

Learn more
Request Details

    scope=https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
    access_type=offline
    redirect_uri=https://kamena9978.herokuapp.com/api/oauth/google/callback
    response_type=code
    client_id=167354703985-vvq2m7brksm8aal41ie8bfnnk4mbm91s.apps.googleusercontent.com

That’s all we know.

**Comment by ParveenBhadooOfficial** [comment]
Show me your Google Credentials Page where you've added your details.

**Comment by johnpatrick9** [comment]
Can I upload a json file or should I send a pic of the credentials page?

**Comment by ParveenBhadooOfficial** [comment]
In Google Credentials at Google Cloud, use https://kamena9978.herokuapp.com/api/oauth/google/callback as auth redirect URL and https://kamena9978.herokuapp.com as auth domain.

See where to do what: https://github.com/ParveenBhadooOfficial/Bhadoo-Cloud/blob/master/README.md#get-google_client_id-and-secret

**Comment by johnpatrick9** [comment]
Okay,thank you for the help
